[package]
name = "autodbconv"
default-run = "autodbconv"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "autodbconv"
path = "src/bin/autodbconv.rs"

[[bin]]
name = "ncf2ldf"
path = "src/bin/ncf2ldf.rs"

[dependencies]
